version: "3.8"

services:
  flask1:
    build:
      context: .
      dockerfile: dockerfile
    container_name: flask1
    networks:
      toshiro_net:
        ipv4_address: 192.168.1.16

  flask2:
    build:
      context: .
      dockerfile: dockerfile
    container_name: flask2
    networks:
      toshiro_net:
        ipv4_address: 192.168.1.17

  flask3:
    build:
      context: .
      dockerfile: dockerfile
    container_name: flask3
    networks:
      toshiro_net:
        ipv4_address: 192.168.1.18

  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: toshiro
    ports:
      - "3306:3306"
    volumes:
      - ./banco.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      toshiro_net:
        ipv4_address: 192.168.1.10

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "4500:4500"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - flask1
      - flask2
      - flask3
    networks:
      toshiro_net:
        ipv4_address: 192.168.1.11

networks:
  toshiro_net:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.1.0/24